import { ideas } from './ideas';
export type Article = { slug:string; title:string; category:string; date:string; readingTime:string; summary:string; ruleReminder:string; relatedIdeas:string[]; body:string[] };

export const articles: Article[] = [
{slug:'build-the-window-space-scene',title:'Build the Window Space Scene',category:'Make the Window Display',date:'2026-07-09',readingTime:'5 min',summary:'A cohesive plan for recreating the star-filled bay window: hanging foil stars, ringed planets and one bold cardboard rocket.',ruleReminder:'Keep every piece inside a window you control or have permission to decorate.',relatedIdeas:['foil-star-window-constellation','cardboard-rocket-window'],body:['Start with the background. Cut lots of small stars first, because they make the window feel full even before the centrepiece goes in. Tape some directly inside the glass and hang others from thread so they float at different heights.','Add three or four ringed planets next. Use the same cardboard-and-marker style for each planet so the display looks like one planned scene rather than separate craft projects. Put planets in corners and lower panes where their round shapes break up the stars.','Make the rocket last and make it the biggest object. A foil body, coloured nose cone, porthole and fins are enough. Place it low in the window so it looks as if it is launching upward through the constellation.','Before photographing it, stand outside and check the composition: largest rocket low, biggest stars near the sides, smaller stars sprinkled everywhere, and no private letters, house numbers or faces visible through the glass.']},
{slug:'build-the-fence-and-garden-launchpad',title:'Build the Fence and Garden Launchpad',category:'Make the Fence Display',date:'2026-07-09',readingTime:'6 min',summary:'Turn a private fence or front garden into the cardboard launch scene from the photos using bunting, moons, placards and a standing rocket.',ruleReminder:'Use only your own fence, railings, garden or a place where you have clear permission; keep pavements and shared access clear.',relatedIdeas:['space-bunting-garland','front-garden-rocket-launch'],body:['Begin with a bunting line because it visually ties the whole fence together. Alternate foil, black and brown-card triangles, then add one simple symbol to each flag: star, planet, rocket or moon.','Next, make the large background shapes. Big cardboard moons and ringed planets read clearly from a distance, especially when they are placed low on the fence or staked among plants. Repeat the same silver-and-cardboard palette to keep everything cohesive.','Build one hero rocket for the centre. It can be a tall box, a flattened cardboard shape or a panel tied safely to railings. Add a foil cone, porthole and oversized fins so it matches the handmade rocket in the images.','Finish with placards. A sign such as “PUBLIC CHEERFULNESS” or “Front Garden Launchpad” gives the display a friendly reason to exist. Keep signs inside your boundary and remove anything loose before wind turns the space programme into litter.']},
{slug:'build-the-door-bin-and-ufo-details',title:'Build the Door, Bin and UFO Details',category:'Make the Extra Props',date:'2026-07-09',readingTime:'5 min',summary:'Use the smaller decorations from the images to extend the theme across a door, wheelie bin or doorstep without making the display messy.',ruleReminder:'Do not cover locks, handles, letterboxes, bin mechanisms, collection routes, steps or pavements.',relatedIdeas:['wheelie-bin-space-station','flying-saucer-and-alien'],body:['For the door, repeat the simplest motif: foil stars. Five to nine lightweight stars on flat door panels can echo the window display without blocking handles, locks, bells or the letterbox. Add a short bunting strand only if it stays fully within your doorway.','For the wheelie bin, build decorations as removable panels. A cardboard control panel, foil stars, a ringed planet badge and two pretend telescope tubes can turn the bin into a space station for a photo, then lift off before collection day.','For the doorstep, make one small UFO rather than a pile of props. Paper plates or cardboard circles covered in foil create the saucer, clear packaging makes a dome, and a green paper alien becomes the pilot. Keep it stable and away from where people step.','The trick is repetition, not quantity. Stars, planets, rockets, bunting and friendly placards appear again and again in the photos, so choose two or three of those shapes and repeat them across each surface.']},
{slug:'materials-and-style-guide-for-cardboard-space',title:'Materials and Style Guide for Cardboard Space',category:'Cohesion Guide',date:'2026-07-09',readingTime:'4 min',summary:'How to make all the decorations feel like they belong together: one colour palette, repeated shapes and gloriously obvious recycled materials.',ruleReminder:'Use removable, lightweight materials and avoid sharp edges, permanent fixings or public-property attachments.',relatedIdeas:['paper-planet-rings','public-cheerfulness-placards'],body:['Pick a tight palette: silver foil, plain brown cardboard, black marker, white paper and one accent colour such as red or green. The images feel cohesive because almost every object uses that same low-budget space vocabulary.','Repeat five shapes: stars, ringed planets, moons, rockets and bunting triangles. You can change the size and surface, but keep the shapes recognisable. A planet on a window, a planet on a fence and a planet on a bin should all look like cousins.','Let the handmade texture show. Creases in foil, marker lines, visible cardboard edges and slightly uneven stars are part of the charm. Do not over-polish it; the point is public cheerfulness, not aerospace procurement.','Use signs sparingly to explain the scene. One bold placard can name the whole display, while smaller labels can add jokes. If every object has a paragraph, passers-by will need a reading list instead of a smile.']},
];

export const articleBySlug = (slug:string) => articles.find(a=>a.slug===slug);
export const latestArticle = articles[0];
export const relatedIdeaObjects = (article: Article) => article.relatedIdeas.map(s=>ideas.find(i=>i.slug===s)).filter(Boolean);
