import { ideas } from './ideas';
export type Article = { slug:string; title:string; category:string; date:string; readingTime:string; summary:string; ruleReminder:string; relatedIdeas:string[]; body:string[] };
export const articles: Article[] = [
{slug:'how-to-binface-without-being-a-menace',title:'How to Binface Your Place Without Being a Menace',category:'How To Binface Your Place',date:'2026-07-08',readingTime:'5 min',summary:'A beginner’s guide to private-property political theatre with fewer headaches and more cardboard.',ruleReminder:'Use property you control or have permission to use.',relatedIdeas:['window-of-intergalactic-compliance','wheelie-bin-press-conference'],body:['Start small: a window sign, a bin speech bubble, or a garden slogan you can remove without drama. The point is voluntary creativity, not making work for councils, neighbours or passing pigeons.','Make the joke clear. Avoid fake official branding, fake polling information, or anything that looks like a council or Electoral Commission notice.','If you are spending meaningful money to campaign locally, pause and check the rules before ordering the giant chrome bin helmet.']},
{slug:'ten-legal-surfaces',title:'Ten Legal Surfaces That Could Probably Handle More Democracy',category:'Display Ideas',date:'2026-07-08',readingTime:'4 min',summary:'Windows, bins, balconies and other surfaces that may be ready for democratic nonsense.',ruleReminder:'Permission beats enthusiasm every time.',relatedIdeas:['beach-hut-embassy','balcony-of-mild-democratic-concern'],body:['Your own window is a classic. Your own garden is a stage. Your own bin is a surprisingly expressive statesperson. A permitted shop window can become a temporary embassy of nonsense.','The key phrase is “your own” or “with permission”. Lamp posts, bus stops, road signs and public bins are not blank canvases, no matter how much they seem to crave satire.']},
{slug:'why-windows-beat-fly-posting',title:'Why Windows Are Better Than Fly-Posting',category:'Compliance Corner',date:'2026-07-08',readingTime:'3 min',summary:'A love letter to transparent glass and not annoying the council.',ruleReminder:'Do not fly-post or sticker public property.',relatedIdeas:['no-fly-posting-victory-lap','window-of-intergalactic-compliance'],body:['Windows are visible, reversible and often already yours. Fly-posting is the opposite: public, messy and likely to transform whimsy into paperwork.','A window display also proves the central theory of this hub: Clacton does not need illegal fly-posting. Clacton has windows.']},
{slug:'wheelie-bin-political-theatre',title:'The Beginner’s Guide to Wheelie Bin Political Theatre',category:'Clacton Nonsense',date:'2026-07-08',readingTime:'4 min',summary:'How to let a bin speak without blocking a pavement or declaring war on collection day.',ruleReminder:'Keep bins safe, accessible and on your property.',relatedIdeas:['wheelie-bin-press-conference','cardboard-constitution'],body:['A wheelie bin has presence. It has gravitas. It has usually seen things. A simple speech bubble can turn it into the nation’s least polished spokesperson.','Do not obstruct pavements, roads, collection points, mirrors or sightlines. Remove decorations when needed and keep the joke lightweight.']},
{slug:'how-to-make-compliance-funny',title:'How to Make Compliance Funny',category:'Compliance Corner',date:'2026-07-08',readingTime:'5 min',summary:'The paperwork is part of the punchline when handled with care.',ruleReminder:'Avoid legal certainty claims; check applicable rules.',relatedIdeas:['shopfront-surrender','no-fly-posting-victory-lap'],body:['Compliance does not have to be beige. A sign reading “This nonsense is on private property with permission” is both useful and oddly funny.','Be transparent that your display is unofficial. Do not imply authorisation you do not have, and do not collect voter details, addresses or political opinions.']},
{slug:'golden-bin-awards',title:'The Golden Bin Awards: What Makes a Display Worthy?',category:'The Golden Bin Awards',date:'2026-07-08',readingTime:'4 min',summary:'Invented awards for fictional examples of lawful ridiculousness.',ruleReminder:'Awards on this site are static editorial jokes, not live submissions.',relatedIdeas:['beach-hut-embassy','social-profile-occupation'],body:['A Golden Bin display is creative, removable, safe, permission-based and obviously parody. Bonus points for cardboard grandeur and suspiciously formal wording.','There is no submission form, no judging database and no secret spreadsheet of addresses. The awards are editorial inspiration, not a campaign operation.']},
];
export const articleBySlug = (slug:string) => articles.find(a=>a.slug===slug);
export const latestArticle = articles[0];
export const relatedIdeaObjects = (article: Article) => article.relatedIdeas.map(s=>ideas.find(i=>i.slug===s)).filter(Boolean);
