export type Idea = { slug:string; title:string; category:string; description:string; difficulty:'Easy'|'Medium'|'Absurd'; cost:'£0'|'£'|'££'; time:string; ruleReminder:string; body:string[] };
export const ideas: Idea[] = [
{slug:'window-of-intergalactic-compliance',title:'The Window of Intergalactic Compliance',category:'Windows',description:'Create a hand-written window sign declaring your home a temporary zone of constitutional binfulness.',difficulty:'Easy',cost:'£0',time:'20 minutes',ruleReminder:'Keep it inside your own window and avoid fake official notices.',body:['One sheet of paper can carry a surprising amount of intergalactic authority when taped inside a window you control. Try a slogan, a mock proclamation, or a polite warning that democracy has entered the hallway.','Do not copy official notices or imply council approval. Handmade is funnier and safer.']},
{slug:'wheelie-bin-press-conference',title:'The Wheelie Bin Press Conference',category:'Bins',description:'Place a speech bubble near your own bin, on your own property, and let it issue a formal statement.',difficulty:'Easy',cost:'£',time:'30 minutes',ruleReminder:'Your bin, your property, no pavement obstruction.',body:['Give your own bin a cardboard speech bubble and a constitutional crisis. Keep it tucked safely on private land so pedestrians, wheels and democracy can all pass freely.','Suggested vibe: absurdly formal. Suggested budget: suspiciously low.']},
{slug:'balcony-of-mild-democratic-concern',title:'The Balcony of Mild Democratic Concern',category:'Balconies',description:'Use bunting, cardboard and suspiciously serious wording to create a display that worries neighbours in a lawful way.',difficulty:'Medium',cost:'£',time:'1 hour',ruleReminder:'Check tenancy, lease, landlord and safety rules first.',body:['Balconies offer theatre, wind and potential paperwork. Use lightweight decorations, secure everything safely, and check building rules before hoisting democracy into the breeze.']},
{slug:'shopfront-surrender',title:'The Shop Window Surrender',category:'Shops',description:'A business with permission can create a small, funny display saying it has voluntarily entered the Binface Zone.',difficulty:'Medium',cost:'£',time:'45 minutes',ruleReminder:'Only with owner/manager permission and no misleading official claims.',body:['A shop window can become a tiny magazine cover for lawful nonsense. Make it clear it is a voluntary parody display, not campaign HQ, not an official notice, and not a data collection point.']},
{slug:'social-profile-occupation',title:'The Social Profile Occupation',category:'Social Profiles',description:'Change your profile header or bio to something suitably ridiculous, without pretending to be official.',difficulty:'Easy',cost:'£0',time:'10 minutes',ruleReminder:'Do not impersonate candidates, councils, election bodies or campaigns.',body:['No ladders. No printing. Just a joke in a place you control. Keep parody obvious, avoid impersonation, and do not harvest people’s politics.']},
{slug:'beach-hut-embassy',title:'The Beach Hut Embassy',category:'Beach Huts',description:'A beach hut can become an intergalactic consulate, provided the owner agrees and no local rules are angered.',difficulty:'Absurd',cost:'££',time:'2 hours',ruleReminder:'Owner permission and local hut rules are mandatory Earth customs.',body:['Diplomatic relations with seagulls are optional. Permission is not. Keep signs secure, removable and respectful of local rules.']},
{slug:'no-fly-posting-victory-lap',title:'The No-Fly-Posting Victory Lap',category:'Things Not To Do',description:'Celebrate the radical idea that public property is not your personal sticker album.',difficulty:'Easy',cost:'£0',time:'Forever',ruleReminder:'Do not put posters or stickers on public property.',body:['The most law-abiding display may be the one you do not stick to a lamp post. Public property belongs to the public, not to your marker pen’s destiny.']},
{slug:'cardboard-constitution',title:'The Cardboard Constitution',category:'Handmade Displays',description:'Use cardboard, marker pens and excessive seriousness to create a one-household democratic manifesto.',difficulty:'Medium',cost:'£',time:'1 hour',ruleReminder:'Keep it on private land and do not mimic official documents.',body:['Cardboard has governed no nations, but it can govern a garden path. Write a playful manifesto, keep claims clearly jokey, and hide private details if photographed.']},
];
export const ideaBySlug = (slug:string) => ideas.find(i=>i.slug===slug);
