export type Idea = { slug:string; title:string; category:string; description:string; difficulty:'Easy'|'Medium'|'Absurd'; cost:'£0'|'£'|'££'; time:string; ruleReminder:string; body:string[] };
export const ideas: Idea[] = [
{slug:'window-of-intergalactic-compliance',title:'The Window of Intergalactic Wonder',category:'Windows',description:'Turn a humble pane of glass into a beacon of bin-flavoured magnificence.',difficulty:'Easy',cost:'£0',time:'20 minutes',ruleReminder:'Keep the masterpiece inside your own window and make parody obvious.',body:['One sheet of paper can carry a surprising amount of intergalactic authority when taped inside a window you control. Try a slogan, a mock proclamation, or a heroic announcement that democracy has entered the hallway wearing a cape.','Handmade wobble is part of the charm. If it looks like it was assembled by a caffeinated space badger with marker pens, excellent.']},
{slug:'wheelie-bin-press-conference',title:'The Wheelie Bin Press Conference',category:'Bins',description:'Give your own bin a speech bubble and let it brief the nation from the driveway.',difficulty:'Easy',cost:'£',time:'30 minutes',ruleReminder:'Your bin, your patch, and clear paths for passing humans.',body:['Give your own bin a cardboard speech bubble and a constitutional crisis. Keep it tucked safely on private land so pedestrians, wheels and democracy can all pass freely.','Suggested vibe: absurdly formal. Suggested budget: suspiciously low. Suggested opening line: “My fellow wheelies.”']},
{slug:'balcony-of-mild-democratic-concern',title:'The Balcony of Bewildered Bunting',category:'Balconies',description:'Deploy lightweight bunting, cardboard drama and wording so grand it may need its own postcode.',difficulty:'Medium',cost:'£',time:'1 hour',ruleReminder:'Check tenancy, lease, landlord and safety rules before the bunting takes flight.',body:['Balconies offer theatre, wind and the chance for bunting to behave like a tiny opera. Use lightweight decorations, secure everything safely, and check building rules before hoisting democracy into the breeze.','If the display makes a seagull pause thoughtfully, you are operating at the correct level.']},
{slug:'shopfront-surrender',title:'The Shop Window Surrender',category:'Shops',description:'With permission, transform a shop window into a cheerful embassy of Binface silliness.',difficulty:'Medium',cost:'£',time:'45 minutes',ruleReminder:'Owner/manager permission first; keep it clearly unofficial and playful.',body:['A shop window can become a tiny magazine cover for nonsense. Make it clear it is a voluntary parody display, not campaign HQ, not an official notice, and not a data collection point.','Add a little theatrical flair: cardboard rosettes, dramatic arrows, or a sign announcing that the biscuits have entered negotiations.']},
{slug:'social-profile-occupation',title:'The Social Profile Spaceport',category:'Social Profiles',description:'Give your profile header or bio a temporary blast of obvious, unofficial absurdity.',difficulty:'Easy',cost:'£0',time:'10 minutes',ruleReminder:'Do not impersonate candidates, councils, election bodies or campaigns.',body:['No ladders. No printing. Just a joke in a place you control. Keep parody obvious, avoid impersonation, and do not harvest people’s politics.','Excellent ingredients include planet emojis, bin puns, and a level of seriousness normally reserved for international treaties about snacks.']},
{slug:'beach-hut-embassy',title:'The Beach Hut Embassy',category:'Beach Huts',description:'A beach hut can become an intergalactic consulate for towels, tea and seagull diplomacy.',difficulty:'Absurd',cost:'££',time:'2 hours',ruleReminder:'Owner permission and local hut rules are mandatory Earth customs.',body:['Diplomatic relations with seagulls are optional. Permission is not. Keep signs secure, removable and respectful of local rules.','Recommended embassy departments: Ministry of Deckchairs, Bureau of Chips, and the Office for Suspiciously Important Buckets.']},
{slug:'no-fly-posting-victory-lap',title:'The Sticker-Free Victory Lap',category:'Party Poopers to Avoid',description:'Celebrate the radical thrill of not turning public property into your personal sticker album.',difficulty:'Easy',cost:'£0',time:'Forever',ruleReminder:'Save posters and stickers for places you control or have permission to use.',body:['The most gloriously well-behaved display may be the one you do not stick to a lamp post. Public property belongs to the public, not to your marker pen’s destiny.','Take a victory lap past a pristine bus stop and whisper, “Not today, chaos.”']},
{slug:'cardboard-constitution',title:'The Cardboard Constitution',category:'Handmade Displays',description:'Use cardboard, marker pens and theatrical seriousness to create a one-household manifesto.',difficulty:'Medium',cost:'£',time:'1 hour',ruleReminder:'Keep it on private land and clearly jokey, with private details out of photos.',body:['Cardboard has governed no nations, but it can govern a garden path. Write a playful manifesto, keep claims clearly jokey, and hide private details if photographed.','Possible clauses: mandatory tea breaks, emergency glitter reserves, and immediate recognition of the bin as a local thought leader.']},
];
export const ideaBySlug = (slug:string) => ideas.find(i=>i.slug===slug);
